name: Pull Request Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  changes:
    uses: ./.github/workflows/changes.yaml
    if: startsWith(github.head_ref, 'release') != true
    permissions:
      pull-requests: read
  e2e_tests:
    needs: changes
    uses: ./.github/workflows/e2e.yaml
    if: needs.changes.outputs.e2e == 'true' && github.event.pull_request.merged == true && github.event.pull_request.head.repo.full_name != github.repository
    secrets: inherit
  