name: Push to main

on:
  push:
    branches:
      - main
jobs:
  changes:
    uses: ./.github/workflows/changes.yaml
    permissions:
      pull-requests: read
  e2e_tests:
    needs: changes
    uses: ./.github/workflows/e2e.yaml
    if: needs.changes.outputs.e2e == 'true'
    secrets: inherit
  